In [2]:
import numpy as np

In [17]:
data = np.arange(64*2).reshape(2,4,4,4)

In [18]:
data.shape

(2, 4, 4, 4)

In [19]:
sliced = np.vstack(np.split(data,2,axis=1))

In [20]:
sliced.shape

(4, 2, 4, 4)

In [21]:
sliced2 = np.vstack(np.split(sliced,2,axis=2))

In [22]:
sliced2.shape

(8, 2, 2, 4)

In [23]:
sliced_final = np.vstack(np.split(sliced2,2,axis=3))

In [24]:
sliced_final.shape

(16, 2, 2, 2)

[[[[ 0  1]
   [ 4  5]]

  [[16 17]
   [20 21]]]


 [[[32 33]
   [36 37]]

  [[48 49]
   [52 53]]]


 [[[ 8  9]
   [12 13]]

  [[24 25]
   [28 29]]]


 [[[40 41]
   [44 45]]

  [[56 57]
   [60 61]]]


 [[[ 2  3]
   [ 6  7]]

  [[18 19]
   [22 23]]]


 [[[34 35]
   [38 39]]

  [[50 51]
   [54 55]]]


 [[[10 11]
   [14 15]]

  [[26 27]
   [30 31]]]


 [[[42 43]
   [46 47]]

  [[58 59]
   [62 63]]]]


In [49]:
data = np.arange(4).reshape(2,2)

In [50]:
axes_rots = [(1,0), (0,1)]
k_list = range(4)
for k in k_list:
    for axes_rot in axes_rots:
        print(np.rot90(data.copy(), k, axes_rot))

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[2 0]
 [3 1]]
[[1 3]
 [0 2]]
[[3 2]
 [1 0]]
[[3 2]
 [1 0]]
[[1 3]
 [0 2]]
[[2 0]
 [3 1]]


In [59]:
flip1 = range(2)
flip2 = range(2)
transposes = [(0,1),(1,0)]
all_d = []
for f1 in flip1:
    for f2 in flip2:
        for t in transposes:
            d = data.copy()
            if f1:
                d = np.flip(d,axis=0)
            if f2:
                d = np.flip(d,axis=1)    
            d = tuple(np.transpose(d,axes=t).reshape([-1]))
            all_d.append(d)
            print(d)
            print('')
len(set(all_d))

(0, 1, 2, 3)

(0, 2, 1, 3)

(1, 0, 3, 2)

(1, 3, 0, 2)

(2, 3, 0, 1)

(2, 0, 3, 1)

(3, 2, 1, 0)

(3, 1, 2, 0)



8

In [62]:
data = np.arange(8).reshape(2,2,2)

In [63]:
flip1 = range(2)
flip2 = range(2)
flip3 = range(2)
transposes = [(0,1,2),(0,2,1),(1,0,2),(1,2,0),(2,0,1),(2,1,0)]
all_d = []
for f1 in flip1:
    for f2 in flip2:
        for f3 in flip3:        
            for t in transposes:
                d = data.copy()
                if f1:
                    d = np.flip(d,axis=0)
                if f2:
                    d = np.flip(d,axis=1)          
                if f3:
                    d = np.flip(d,axis=2)
                d = tuple(np.transpose(d,axes=t).reshape([-1]))
                all_d.append(d)
len(set(all_d))

48

In [3]:
import data.transformation as transformation
import numpy as np
data = np.arange(16).reshape(2,2,2,2)
print(data)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [2]:
rot = transformation.rotate_3d(data)
print(rot)

[[[[ 5  7]
   [ 4  6]]

  [[ 1  3]
   [ 0  2]]]


 [[[13 15]
   [12 14]]

  [[ 9 11]
   [ 8 10]]]]


In [11]:
transl = transformation.translate_3d(data)
print(transl)

[[[[ 1  0]
   [ 3  2]]

  [[ 5  4]
   [ 7  6]]]


 [[[ 9  8]
   [11 10]]

  [[13 12]
   [15 14]]]]
